version: "3.7"

services:
  ruby:
    command: bundle exec rackup --host 0.0.0.0
    environment:
      BUNDLE_APP_CONFIG: /app/.bundle
      RUBYOPT: -EUTF-8
      SHELL: /bin/sh
      TZ: Asia/Tokyo
    image: ruby:2.6.5
    ports:
      - 127.0.0.1:9292:9292
    volumes:
      - .:/app
    working_dir: /app
